name: nour
description: "A new Flutter project."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version and build number for your application
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: 5.6.8
  firebase_storage: ^12.4.6
  file_picker: ^10.1.9
  firebase_auth_web: ^5.14.3
  http: ^1.4.0
  html: ^0.15.0
  cupertino_icons: ^1.0.8
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
